import test from 'node:test';
import assert from 'node:assert/strict';
import { calculateBmi, deriveCmrf, classifySld, calculateFib4, evaluateFib4, evaluatePlatelets, shouldShowNit, interpretNit } from '../clinical-rules.js';

test('BMI helper rounds to one decimal place',()=>assert.equal(calculateBmi(182,88),26.6));
test('CMRF is derived from numeric inputs without manual checkboxes',()=>{const c=deriveCmrf({sex:'male',bmi:22.5,waist:90,hba1c:5.8,sbp:125,dbp:78,tg:120,hdl:55,diagnosedDiabetes:false,antihypertensiveTreatment:false,lipidTreatment:false});assert.equal(c.statuses.glucose,true);assert.equal(c.count,1)});
test('waist is requested only when it can determine the final CMRF',()=>{const c=deriveCmrf({sex:'male',bmi:22.5,waist:null,hba1c:5.4,sbp:120,dbp:75,tg:110,hdl:60,diagnosedDiabetes:false,antihypertensiveTreatment:false,lipidTreatment:false});assert.equal(c.needsWaist,true)});
test('MASLD and MetALD alcohol boundaries follow Japanese 2026 thresholds',()=>{const c={hasAny:true,count:1,needsWaist:false,canRuleOutAll:false,unknownKeys:[]};assert.equal(classifySld({steatosis:true,sex:'male',alcoholGWeek:209,otherCause:false},c).id,'masld');assert.equal(classifySld({steatosis:true,sex:'male',alcoholGWeek:210,otherCause:false},c).id,'metald');assert.equal(classifySld({steatosis:true,sex:'male',alcoholGWeek:420,otherCause:false},c).id,'metald');assert.equal(classifySld({steatosis:true,sex:'male',alcoholGWeek:421,otherCause:false},c).id,'ald')});
test('FIB-4 calculation preserves full precision for classification',()=>{const score=calculateFib4({age:65,ast:40,alt:45,plateletsWan:18.5});assert.ok(Math.abs(score-2.0950546816214244)<1e-12)});
test('age 66 uses the 2.0 lower FIB-4 threshold',()=>{assert.equal(evaluateFib4(65,1.5).id,'intermediate');assert.equal(evaluateFib4(66,1.5).id,'low');assert.equal(evaluateFib4(66,2.0).id,'intermediate');assert.equal(evaluateFib4(66,2.68).id,'high')});
test('platelet supporting bands use 15 and 20 man/uL boundaries',()=>{assert.equal(evaluatePlatelets(14.9).id,'high');assert.equal(evaluatePlatelets(15).id,'intermediate');assert.equal(evaluatePlatelets(20).id,'intermediate');assert.equal(evaluatePlatelets(20.1).id,'low')});
test('NIT output remains suggestive rather than definitive',()=>{const r=interpretNit({vcteKpa:8.2,swe:'',sweUnit:'kpa',mreKpa:'',elf:'',type4Collagen7s:'',m2bpgi:''});assert.equal(r[0].status,'f2');assert.match(r[0].detail,/示唆/)});
test('NIT severity uses green below F2 and yellow at or above F2',()=>{const r=interpretNit({vcteKpa:7.9,swe:'',sweUnit:'kpa',mreKpa:'',elf:'',type4Collagen7s:'',m2bpgi:''});assert.equal(r[0].status,'below');assert.equal(r[0].severityLabel,'≥F2未満')});
test('MRE and ELF can escalate to F4 red status at guideline cutoffs',()=>{const r=interpretNit({vcteKpa:20,swe:'',sweUnit:'kpa',mreKpa:4.45,elf:11.8,type4Collagen7s:7,m2bpgi:2});const byKey=Object.fromEntries(r.map(x=>[x.key,x]));assert.equal(byKey.vcte.status,'f2');assert.equal(byKey.mre.status,'f4');assert.equal(byKey.elf.status,'f4');assert.equal(byKey.type4.status,'f2');assert.equal(byKey.m2bpgi.status,'f2')});

test('MASLD can coexist with another steatosis etiology',()=>{const c={hasAny:true,count:1,needsWaist:false,canRuleOutAll:false,unknownKeys:[]};const r=classifySld({steatosis:true,sex:'male',alcoholGWeek:0,otherCause:true},c);assert.equal(r.id,'masld');assert.match(r.title,/特定成因併存/)});

test('low-risk FIB-4 with preserved platelets does not request second-line NIT',()=>{assert.equal(shouldShowNit({fib4Evaluation:evaluateFib4(55,0.9),plateletsWan:25}),false)});

test('waist remains relevant after a value is entered so it can be reviewed or corrected',()=>{const c=deriveCmrf({sex:'male',bmi:22.5,waist:95,hba1c:5.4,sbp:120,dbp:75,tg:110,hdl:60,diagnosedDiabetes:false,antihypertensiveTreatment:false,lipidTreatment:false});assert.equal(c.waistRelevant,true);assert.equal(c.needsWaist,false);assert.equal(c.statuses.body,true)});
test('Japanese 2026 waist criterion is strictly greater than 94/80 cm',()=>{const base={bmi:22.5,hba1c:5.4,sbp:120,dbp:75,tg:110,hdl:60,diagnosedDiabetes:false,antihypertensiveTreatment:false,lipidTreatment:false};assert.equal(deriveCmrf({...base,sex:'male',waist:94}).statuses.body,false);assert.equal(deriveCmrf({...base,sex:'male',waist:94.1}).statuses.body,true);assert.equal(deriveCmrf({...base,sex:'female',waist:80}).statuses.body,false);assert.equal(deriveCmrf({...base,sex:'female',waist:80.1}).statuses.body,true)});
test('specific-cause SLD waits until decision-relevant CMRFs are resolved',()=>{const c=deriveCmrf({sex:'male',bmi:22.5,waist:null,hba1c:5.4,sbp:120,dbp:75,tg:110,hdl:60,diagnosedDiabetes:false,antihypertensiveTreatment:false,lipidTreatment:false});const r=classifySld({steatosis:true,sex:'male',alcoholGWeek:0,otherCause:true},c);assert.equal(r.id,'pending');assert.deepEqual(r.missing,['waist'])});
test('FIB-4 classification uses the unrounded value at the high-risk boundary',()=>{assert.equal(evaluateFib4(60,2.6716).id,'high');assert.equal(evaluateFib4(60,1.299).id,'low')});
